<?php

namespace frontend\models;

class Book extends \yii\db\ActiveRecord {
    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }

    public static function getAll() {
       $data = self::find()->all();
        return $data;
    }
}